# Generated by Django 6.0 on 2025-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_national', models.CharField(blank=True, max_length=12, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(blank=True, max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1)),
                ('date_naissance', models.DateField()),
                ('nom_pere', models.CharField(max_length=100)),
                ('prenom_pere', models.CharField(blank=True, max_length=100)),
                ('nom_mere', models.CharField(max_length=100)),
                ('prenom_mere', models.CharField(blank=True, max_length=100)),
                ('nationalite', models.CharField(default='Congolaise', max_length=100)),
                ('adresse_actuelle', models.CharField(blank=True, max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
