# Generated by Django 6.0 on 2025-12-09 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeNaissance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_acte', models.CharField(blank=True, max_length=20, unique=True)),
                ('date_etablissement', models.DateField(auto_now_add=True)),
                ('lieu_etablissement', models.CharField(default='Commune de Démonstration', max_length=150)),
                ('officier', models.CharField(default="Officier de l'état civil (démo)", max_length=150)),
                ('personne', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acte_naissance', to='personnes.personne')),
            ],
        ),
    ]
