# Generated by Django 6.0 on 2025-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0002_actenaissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='type_enregistrement',
            field=models.CharField(choices=[('NAISSANCE', 'Enregistrement Naissance'), ('ADULTE', 'Enregistrement Adulte')], default='NAISSANCE', max_length=10, verbose_name="Type d'enregistrement"),
        ),
        migrations.AlterField(
            model_name='personne',
            name='numero_national',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
