# Generated by Django 6.0 on 2025-12-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnes', '0003_personne_type_enregistrement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='type_acte',
            field=models.CharField(choices=[('NORMAL', 'Naissance déclarée'), ('TARDIF', 'Acte établi après recensement adulte')], default='NORMAL', max_length=10, verbose_name="Type d'acte"),
        ),
    ]
