# Generated by Django 5.1.13 on 2025-12-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personnes", "0005_journalaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actenaissance",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="journalaudit",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="personne",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
